package Scratch.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new FieldDef_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new FieldDefRef_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new FieldDefinitions_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new FieldGroup_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new FieldPropertyA_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new FieldPropertyB_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new FieldDefRef_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa1187cL), MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2a9f35e4L), MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2a9f35e1L), MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa3187dL), MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11878L), MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11874L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2a9f35e4L)).seal();
}
