package Scratch.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int FieldDef = 0;
  public static final int FieldDefRef = 1;
  public static final int FieldDefinitions = 2;
  public static final int FieldGroup = 3;
  public static final int FieldProperty = 4;
  public static final int FieldPropertyA = 5;
  public static final int FieldPropertyB = 6;
  public static final int TypedProperties = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L);
    builder.put(0x39c1fead2aa1187cL, FieldDef);
    builder.put(0x39c1fead2a9f35e4L, FieldDefRef);
    builder.put(0x39c1fead2a9f35e1L, FieldDefinitions);
    builder.put(0x39c1fead2aa3187dL, FieldGroup);
    builder.put(0x39c1fead2aa11870L, FieldProperty);
    builder.put(0x39c1fead2aa11878L, FieldPropertyA);
    builder.put(0x39c1fead2aa11874L, FieldPropertyB);
    builder.put(0x39c1fead2aa3d985L, TypedProperties);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
