package Scratch.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFieldDef = createDescriptorForFieldDef();
  /*package*/ final ConceptDescriptor myConceptFieldDefRef = createDescriptorForFieldDefRef();
  /*package*/ final ConceptDescriptor myConceptFieldDefinitions = createDescriptorForFieldDefinitions();
  /*package*/ final ConceptDescriptor myConceptFieldGroup = createDescriptorForFieldGroup();
  /*package*/ final ConceptDescriptor myConceptFieldProperty = createDescriptorForFieldProperty();
  /*package*/ final ConceptDescriptor myConceptFieldPropertyA = createDescriptorForFieldPropertyA();
  /*package*/ final ConceptDescriptor myConceptFieldPropertyB = createDescriptorForFieldPropertyB();
  /*package*/ final ConceptDescriptor myConceptTypedProperties = createDescriptorForTypedProperties();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFieldDef, myConceptFieldDefRef, myConceptFieldDefinitions, myConceptFieldGroup, myConceptFieldProperty, myConceptFieldPropertyA, myConceptFieldPropertyB, myConceptTypedProperties);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.FieldDef:
        return myConceptFieldDef;
      case LanguageConceptSwitch.FieldDefRef:
        return myConceptFieldDefRef;
      case LanguageConceptSwitch.FieldDefinitions:
        return myConceptFieldDefinitions;
      case LanguageConceptSwitch.FieldGroup:
        return myConceptFieldGroup;
      case LanguageConceptSwitch.FieldProperty:
        return myConceptFieldProperty;
      case LanguageConceptSwitch.FieldPropertyA:
        return myConceptFieldPropertyA;
      case LanguageConceptSwitch.FieldPropertyB:
        return myConceptFieldPropertyB;
      case LanguageConceptSwitch.TypedProperties:
        return myConceptTypedProperties;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFieldDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldDef", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa1187cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550365046908");
    b.version(2);
    b.aggregate("properties", 0x39c1fead2aa11880L).target(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11870L).optional(true).ordered(true).multiple(true).origin("4161887550365046912").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldDefRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldDefRef", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2a9f35e4L);
    b.class_(false, false, false);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550364923364");
    b.version(2);
    b.associate("field", 0x39c1fead2a9f35e7L).target(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa1187cL).optional(false).origin("4161887550364923367").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldDefinitions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldDefinitions", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2a9f35e1L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550364923361");
    b.version(2);
    b.aggregate("fieldDefs", 0x39c1fead2a9f35e9L).target(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa1187cL).optional(true).ordered(true).multiple(true).origin("4161887550364923369").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldGroup() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldGroup", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa3187dL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550365177981");
    b.version(2);
    b.aggregate("fields", 0x39c1fead2aa31891L).target(0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2a9f35e4L).optional(true).ordered(true).multiple(true).origin("4161887550365178001").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldProperty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldProperty", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11870L);
    b.class_(false, true, false);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550365046896");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldPropertyA() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldPropertyA", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11878L);
    b.class_(false, false, false);
    b.super_("Scratch.structure.FieldProperty", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11870L);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550365046904");
    b.version(2);
    b.property("value", 0x39c1fead2aa11879L).type(PrimitiveTypeId.INTEGER).origin("4161887550365046905").done();
    b.alias("a");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldPropertyB() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "FieldPropertyB", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11874L);
    b.class_(false, false, false);
    b.super_("Scratch.structure.FieldProperty", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa11870L);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550365046900");
    b.version(2);
    b.property("value", 0x39c1fead2aa11875L).type(PrimitiveTypeId.STRING).origin("4161887550365046901").done();
    b.alias("b");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypedProperties() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Scratch", "TypedProperties", 0x12e8d36ff50844b5L, 0x816a8a6eb724d0d3L, 0x39c1fead2aa3d985L);
    b.class_(false, false, true);
    b.origin("r:d41aaaeb-6eb3-4a22-aefa-c4f7cea397e0(Scratch.structure)/4161887550365227397");
    b.version(2);
    b.property("someIntProperty", 0x39c1fead2aa3d986L).type(PrimitiveTypeId.INTEGER).origin("4161887550365227398").done();
    b.property("someStringProperty", 0x39c1fead2aa3d989L).type(PrimitiveTypeId.STRING).origin("4161887550365227401").done();
    b.property("someBooleanProperty", 0x39c1fead2aa3d98eL).type(PrimitiveTypeId.BOOLEAN).origin("4161887550365227406").done();
    b.alias("types");
    return b.create();
  }
}
